# If you come from bash you might have to change your $PATH.
export PATH=$PATH:~/.local/bin

# Path to your oh-my-zsh installation.
export ZSH=/home/rookie/.oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="bira"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# kennethreitz, robbyrussell also good
# ZSH_THEME_RANDOM_CANDIDATES=( "bira" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
plugins=(git vi-mode mercurial)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi
export EDITOR=nvim

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
# alias tmux="TERM=screen-256color-bce tmux"
#
alias tl="tasklite"
alias tl-review="sqlite3 -header -column ~/gdrive_rclone/tasklite/main.db \"
    SELECT p.due_date, c.total_done, p.planned, d.planned_done, m.missed_deadlines from 
    -- all tasks that had been planned
    (SELECT DATE(due_utc) AS due_date, count(*) AS planned FROM tasks_view WHERE due_utc IS NOT NULL GROUP BY DATE(due_utc)) p
    LEFT JOIN
    -- all tasks that were done in that day
    (SELECT DATE(closed_utc) AS closed_date, count(*) AS total_done FROM tasks_view WHERE closed_utc IS NOT NULL GROUP BY DATE(closed_utc)) c
    ON c.closed_date = p.due_date
    LEFT JOIN
    -- all planned tasks that got completed on this day
    (SELECT DATE(closed_utc) AS closed_date, DATE(due_utc) AS planned_due, count(*) AS planned_done FROM tasks_view WHERE closed_utc IS NOT NULL AND due_utc IS NOT NULL GROUP BY DATE(closed_utc)) d
    ON d.planned_due = p.due_date
    LEFT OUTER JOIN 
    -- all planned tasks that were done after the due date (ignoring time)
    (SELECT DATE(due_utc) as missed_date, count(*) AS missed_deadlines FROM tasks_view WHERE DATE(due_utc) < DATE(closed_utc) OR  (due_utc IS NOT NULL AND closed_utc IS NULL) GROUP BY DATE(due_utc)) m
    ON  m.missed_date = p.due_date 
    WHERE p.due_date < DATETIME('now')
    ORDER BY p.due_date DESC LIMIT 10\"
"
alias tl-leo="tl query \"closed_utc IS NULL AND DATE(due_utc) <= DATE('now') AND (ready_utc IS NULL OR DATETIME(ready_utc) <= DATETIME('now')) order by due_utc ASC, ready_utc ASC, priority DESC\""
alias tl-leo-all="tl query \"closed_utc IS NULL AND DATE(due_utc) <= DATE('now') order by priority DESC, due_utc ASC\""
alias tl-kesho="tl query \"closed_utc IS NULL AND DATE(due_utc) <= DATE('now', '+1 day') order by priority DESC, due_utc ASC\""
alias tl-unscheduled="tl query \"closed_utc IS NULL AND due_utc IS NULL order by priority DESC\""
alias tl-down="rclone copy gdrive:backups/work_xps ~/gdrive_rclone --update" 
alias tl-up="rclone copy ~/gdrive_rclone gdrive:backups/work_xps --update"
alias tl-remaining="sqlite3 -header -column ~/gdrive_rclone/tasklite/main.db \"SELECT r.due_utc, r.remaining, ROUND((t.planned-r.remaining)*1.0/t.planned, 2) AS completion FROM (SELECT DATE(due_utc) AS due_utc, count(*) AS remaining from tasks_view WHERE DATE(due_utc)<=DATE('now') AND closed_utc IS NULL)r JOIN (SELECT DATE(due_utc) AS due_utc, count(*) AS planned from tasks_view WHERE DATE(due_utc)==DATE('now'))t ON t.due_utc=r.due_utc;\""
# alias tl-remaining="sqlite3 -header -column ~/gdrive_rclone/tasklite/main.db \"SELECT count(*) AS remaining from tasks_view WHERE DATE(due_utc)<=DATE('now') AND closed_utc IS NULL\""
alias tl-plan="tl query \"closed_utc IS NULL AND DATE(due_utc) <= DATE('now') AND (tags IS NULL OR (tags NOT LIKE '%ignore%' AND tags NOT LIKE '%meeting%')) ORDER BY priority desc\""
alias tl-plan-kesho="tl query \"closed_utc IS NULL AND DATE(due_utc) <= DATE('now', '+1 day') AND (tags IS NULL OR (tags NOT LIKE '%routine%' AND tags NOT LIKE '%meeting%')) ORDER BY priority desc\""
alias ledger-budget="ledger --file ~/docs/ledger/blackbook.ledger --period \"this month\"  --exchange Ksh --no-rounding --budget --monthly register ^expenses"


if [ -f ~/.custom_alias ]; then
    source ~/.custom_alias
fi
# prompt dir for agnoster theme
# Check docs here: http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html
# prompt_dir () {
#     prompt_segment blue black "%C"
# }
