#!/bin/bash

# TODO: may be add support for all folders in the projects folder

folders_to_check=(
    '/home/rookie/projects/pomodoro'
    '/home/rookie/docs/ledger'
    '/home/rookie/docs/weekly'
    '/home/rookie/dotfiles'
    '/home/rookie/projects/blog'
    '/home/rookie/vimwiki'
    '/home/rookie/.password-store'
    ) 
folders_not_in_sync=()

for folder in "${folders_to_check[@]}"; do
    cd $folder
    branches_info=$(git branch -vv | grep -E -o 'ahead|behind')
    files_not_commited=$(git status -s)
    if [[ -n $branches_info || -n $files_not_commited ]]; then
        folders_not_in_sync=("${folders_not_in_sync[@]}" $folder)
    else
        pull_result=$(git pull)
        if [[ $pull_result != "Already up to date." ]]; then
            echo $pull_result
        fi
    fi
done


if [[ ${#folders_not_in_sync[@]} -gt 0 ]]; then
    echo -e "The following folders are not in sync" "\033[31m"
    for folder in "${folders_not_in_sync[@]}"; do
        echo -e "\t"$folder
    done
    echo -e "\033[39;49m"
else
    echo "All folders are in sync"
fi
