tableName: tasks
idWidth: 4
idStyle: green
priorityStyle: magenta
dateStyle: dull grey
bodyStyle: dull white
bodyClosedStyle: black
closedStyle: dull grey
dueStyle: yellow
overdueStyle: light red
tagStyle: blue
utcFormat: YYYY-MM-DD H:MI:S

#| Optional, uses the XDG directory per default
#| https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
# dataDir: /custom/path/tasklite
dataDir: ~/gdrive_rclone/tasklite

dbName: main.db
dateWidth: 10
bodyWidth: 10 
prioWidth: 3
headCount: 20
maxWidth: 120
progressBarWidth: 24
